name: Build, Sign & Test Android App

on:
  push:
    branches:
      - new_development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      
      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNKEY }}
          alias: "cedric_alias_key"
          keyStorePassword: "Openbay@taar"
          keyPassword: "Openbay@taar"

      - name: Upload Signed APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-unsigned-signed.apk
          path: app/build/outputs/apk/release/app-release-unsigned-signed.apk

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Android Test APK
        id: android-test-download
        uses: actions/download-artifact@v2
        with:
          name: app-release-unsigned-signed.apk

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set current project
        run: gcloud config set project 'cedric-8cb7d'

      - name: Run Instrumentation Tests in Firebase Test Lab
        env:
          APP_DEBUG_LOCATION: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          ANDROID_TEST_LOCATION: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          DEVICE_MODEL: Nexus9,version=24,locale=en,orientation=landscape
        run: gcloud firebase test android run --type instrumentation --app $APP_DEBUG_LOCATION --test $ANDROID_TEST_LOCATION --device model=$DEVICE_MODEL --use-orchestrator --num-flaky-test-attempts 2
